CREATE TABLE DEFAULT_SCHEMA.PRODUCT (
       item CHAR(20) NOT NULL
     , price INTEGER NOT NULL
     , CONSTRAINT PK_PRODUCT PRIMARY KEY (item)
);

CREATE TABLE DEFAULT_SCHEMA.ACCOUNT (
       key INTEGER NOT NULL CONSTRAINT PK_ACCOUNT PRIMARY KEY AUTOINCREMENT
     , item CHAR(20) NOT NULL
     , num INTEGER NOT NULL
     , date CHAR(10) NOT NULL
     , CONSTRAINT FK_ACCOUNT_1 FOREIGN KEY (item)
                  REFERENCES DEFAULT_SCHEMA.PRODUCT (item)
);

